### ISSUE TITLE
Problembehandlung: User kann sich nicht einloggen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#105]
Mögliche Fehlerquellen:

* Benutzer existiert nicht mehr -> Setup durchlaufen
* Passwort nicht korrekt -> Setup durchlaufen, Passwort zurücksetzen über die Datenbank, FOR-Addon
* Speicherplatz des Hosting-Pakets voll -> Prüfen beim Webhosting

**Comment by skerbis** [comment]
zu 2. neues Passwort über die Console setzen

**Comment by alexplusde** [comment]
4. Datenbank existiert nicht mehr, Seite wird U.U. nur aus dem Cache geladen

**Comment by skerbis** [comment]
@alexplusde wenn die Datenbank nicht funktioniert wird REDAXO 5 garnichts anzeigen

**Comment by alexplusde** [comment]
Wenn die Datenbank vorhanden ist, aber leer, geht das schon.
