### ISSUE TITLE
Einfache Navigation - Parameter erläutern

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#106]
Die Parameter, die erst bei sitemap erklärt werden, sollten bereits für die einfache Navigation erklärt werden: https://github.com/redaxo/docs/blob/master/navigationen.md#factory-einfach

Sonst unverständlich (siehe Slack)

**Comment by polarpixel** [comment]
Najaaa ... wenn man bereits im zweiten Satz erwähnt, dass die möglichen Parameter im nächsten Beispiel (also genau einen Absatz drunter) erklärt werden, dann sollte man das verstehen können, finde ich.
Aber was meint Ihr @skerbis und @dtpop ?

Wenn jemand das verschieben und die textlichen Anschlüsse anpassen will, hab ich nix dagegen, ich würde hier aber nicht tätig werden.

**Comment by skerbis** [comment]
Ich würde die Erläuterung der Parameter evtl. an den Anfang setzen. Im erweiterten Beispiel ist es gut kommentiert und kann so 1:1 nach oben gezogen werden. Von mir aus akzeptiert.

**Comment by skerbis** [comment]
Ist nun weiter oben erläutert.
