### ISSUE TITLE
rex_config_form erläutern

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#107]
Ursprüngliche Idee

https://github.com/redaxo/redaxo/issues/436

Sollte m.E. mit Verweis auf rex_form jedoch in der Rubrik rex_config erläutert werden:
https://redaxo.org/doku/master/konfiguration und mit ein paar einfachen Beispielen erklären, wo und wie dann eine config gesetzt wird.

```
    $form = rex_config_form::factory("addonxyz");
```

`addonxyz` ist der Namespace in der Tabelle `rex_config`

```
    $field = $form->addTextField('field_key');
```

`field_key` ist der Schlüssel in der Tabelle `rex_config`

Absenden-Button wird automatisch hinzugefügt, Speichern wird automatisch durchgeführt - anders als die bisher übliche Schreibweise für config-Formulare

Beispiel für die letztendliche Ausgabe

```
$fragment = new rex_fragment();
$fragment->setVar('class', 'edit', false);
$fragment->setVar('title', $this->i18n('example_title'), false);
$fragment->setVar('body', $form->get(), false);
echo $fragment->parse('core/page/section.php');
```

**Comment by skerbis** [comment]
@alexplusde https://github.com/redaxo/docs/blob/master/konfiguration_form.md
Bitte mal Gegenchecken, ergänzen :-)

**Comment by alexplusde** [comment]
Weitere Erläuterungen ergänzt, es fehlen noch Querverweise von rex_form und rex_config.
