### ISSUE TITLE
Fragmente Bild zu groß

### ISSUE THREAD

**Issue by eaCe** [redaxo/docs#110]
![grafik](https://user-images.githubusercontent.com/2708231/62446400-e77e4180-b762-11e9-918a-e6b5740866bc.png)

Das Bild innerhalb der `<li>` bekommt nicht die Klassen `img-responsive img-zoom`

**Comment by tbaddade** [comment]
Am einfachsten wäre es, dass Bild anders einzusetzen.

**Comment by skerbis** [comment]
@eaCe Danke für den Hinweis, korrigiert: https://github.com/redaxo/docs/commit/1b8866071fdfa95b0a95f725a560c527ba65cb10
