### ISSUE TITLE
Addon-Plugins: update.php und install.php müssen manuell ausgeführt werden

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#111]
Aus der yform install.php stibitzt
```
foreach ($this->getInstalledPlugins() as $plugin) {
    // use path relative to __DIR__ to get correct path in update temp dir
    $file = __DIR__.'/plugins/'.$plugin->getName().'/install.php';

    if (file_exists($file)) {
        $plugin->includeFile($file);
    }
}
```

>Wenn ein Addon re-installiert wird, dann werden die Plugins nicht gleichzeitig auch reinstalliert.
Manche Addons wollen das aber.
dann braucht man den schnipsel von oben zum beispiel
— @gharlan 

(Der Grund, warum 1 Jahr meine update.php und install.php in einem Plugin nie funktioniert haben.)

**Comment by gharlan** [comment]
Also wenn das Plugin direkt (re)installiert wird, greift die update.php schon.
Auch wenn es über `system_plugins` im Addon direkt mit installiert wird.
Aber nicht bei Reinstallation eines Addons.

**Comment by skerbis** [comment]
Wüßte gerade nicht wo ich es unterbringe. Ist eher ein Trick oder?

**Comment by alxndr-w** [comment]
Plugins sollen verschwinden, für mich verschwindet in der Flut von Issues daher die Notwendigkeit, das weiter zu dokumentieren.
