### ISSUE TITLE
Redaktion: Meta Infos bei Kategorien bearbeiten fehlt 

### ISSUE THREAD

**Issue by 191977** [redaxo/docs#113]
Hi,

ich habe eben in der Doku nach der Info gesucht, wie man die Meta Infos von Kategorien ändert. 
Unter Strukturverwaltung>Funktionsbeschreibung>Ändern hätte ich zumindest die Info finden können, dass sich die Editfunktion wie dort beschrieben irgendwie finden lassen muss. Aber es fehlt der Hinweis auf das Plus-Zeichen. Hier ein screenshot der vielleicht hilfreich wäre:
![grafik](https://user-images.githubusercontent.com/47699885/63923598-17a9bf00-ca47-11e9-8d9a-cd2b00f5f0bf.png)

So oder so hätte ich die Info im Bereich Redaktion erwartet. Dort werden Metainfos aber nur am Beispiel eines Artikels beschrieben.

**Comment by skerbis** [comment]
Hier ist's drin: 
https://github.com/redaxo/docs/blob/master/strukturverwaltung.md#meta
