### ISSUE TITLE
Cronjob: Umgebung Skript erläutern

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#115]
Am Eingabefeld steht

> Skript: Ausführung über redaxo/bin/console cronjob:run. Das Skript sollte mittels eines echten Cronjobs regelmäßig aufgerufen werden.

Dies Info wäre auch in der Doku nützlich - einmal unter Console (als Beispiel), einmal unter Cronjob (als Anleitung). Vielleicht mit Hinweis darauf, was ein echter Cronjob ist und dasss man ihn beim Server/Paket des Hosters einrichten muss.

**Comment by gharlan** [comment]
Und auch eine Erläuterung, was für ein Intervall man beim echten Cronjob dann auswählen muss.

**Comment by gharlan** [comment]
Da man in REDAXO ja mehrere Jobs haben kann mit unterschiedlichen Intervallen, finde ich nur die eine Richtung sinnvoll.
Ich hätte daher grob sowas gesagt wie:
> Beim echten Cronjob ist das kleinste Intervall aller REDAXO-Jobs, oder noch kleiner, auszuwählen. Im Zweifel 1 Minute zu nehmen, damit man nichts anpassen muss, falls man mal noch weitere Jobs in REDAXO mit kürzeren Intervallen anlegt.

**Comment by gharlan** [comment]
Und vielleicht noch die Erläuterung, dass der echte Cronjob das Cronjob-Addon anstößt, und dieses dann aber selbst entscheidet, welche Jobs tatsächlich dran sind.

**Comment by alexplusde** [comment]
Schlüssig! Gut, dass wir darüber geschrieben haben.

**Comment by alexplusde** [comment]
Durch die Diskussion in Slack: Gut wäre, wenn man Laufzeit "Skript" als Empfehlung gegenüber Frontend darstellt. Schließlich ist das performanter und nicht besucherabhängig, da bei aufwendigen Cronjobs im Zweifel die Ladezeit der Website sich um viele Sekunden erhöht bei der Ausführung.

**Comment by synonymousz** [comment]
Ohne jetzt genau zu wissen, wie ganz genau das mit den CronjobAddon bei Redaxo läuft:
Meiner Meinung nach macht es keinen Sinn, den Cronjob auf den kleinsten Interval zu legen. Hast du einen Cronjob, der alle 10 Minuten ausgeführt werden soll und einen der alle 11 Minuten ausgeführt werden soll, wird der zweite nur alle 20 Minuten ausgeführt. (Da nur alle 10 Minuten geschaut wird, ob 11 Minuten um sind)
-> Deswegen am besten immer auf 1 Minute

**Comment by alexplusde** [comment]
@synonymousz möchtest du dazu die entsprechende Stelle der Doku überarbeiten?

**Comment by synonymousz** [comment]
Wäre das jetzt nur der Passus für die Intervalempfehlung gewesen ja, aber da fehlt noch ein ganzer Absatz wie der normale Cronjob das Cronjob-Addon aufruft, deswegen sollte das jemand machen der sich besser mit Redaxo auskennt als ich. 

Vielleicht ist ja der fleißige @crydotsnake dafür zu haben 👍

**Comment by crydotsnake** [comment]
Hallo!. Wo wird Hilfe benötigt? :).

**Comment by skerbis** [comment]
@crydotsnake siehe oben

**Comment by skerbis** [comment]
@crydotsnake ping

**Comment by crydotsnake** [comment]
?

**Comment by skerbis** [comment]
Wolltest du das nicht übernehmen? @crydotsnake

**Comment by crydotsnake** [comment]
Ups. Das hab ich wohl komplett aus den Augen verloren 😳😅

**Comment by skerbis** [comment]
@omphteliba Hallo Oliver :: Ich sehe dazu hast du schon was geschrieben in deinem Fork. Möchtest du es nicht als PR einreichen?

**Comment by omphteliba** [comment]
> @omphteliba Hallo Oliver :: Ich sehe dazu hast du schon was geschrieben in deinem Fork. Möchtest du es nicht als PR einreichen?

Ja klar, gerne... hab ich wohl vergessen.
