### ISSUE TITLE
Redaxo i18n-Keys (zur Laufzeit) ergänzen

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#116]
DH
> Guten Morgen, wie kann ich denn in Redaxo i18n-Keys ergänzen und dabei update-fähig bleiben (z.B. für einen Feldnamen vom AddOn global_settings)?

@staabm 
> In der boot.php deines projekt addons die keys ins i18n programatisch einfügen

https://github.com/redaxo/redaxo/blob/ac51f37fa5a4e2d6f85c4b61c1c557db799fa7de/redaxo/src/core/lib/util/i18n.php#L305

```
public static function addMsg($key, $msg)
```

@gharlan 
> Oder als lang Datei im project Addon..

**Comment by skerbis** [comment]
ES wäre dazu ein Menüpunkt "Übersetzung" sinnvoll
