### ISSUE TITLE
Fragmente: Liste unzulässiger Parameter

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#118]
**Description / Beschreibung**
z.B: filename gibt den Dateinamen des Fragments aus und kann auch nicht überschrieben werden durch $fragment->setVar('filename', "xyz.abc", false);

Eine Liste unzulässiger Parameter wäre hilfreich.

**Affected versions / Verwendete Versionen**
REDAXO: 5.*
PHP: *
Browser: *
AddOns: *

**Comment by skerbis** [comment]
Wie lautet die Liste?

**Comment by alexplusde** [comment]
Die hätte ich gerne!

**Comment by DanielWeitenauer** [comment]
Hi, das Problem ist die Abfrage über den Magic Getter. Wenn die Variable über getVar abgefragt würde, würde der ursprüngliche Wert heraus kommen. Da `__get()` jedoch erst anspringt, wenn die Property nicht existiert, gibt es bei den internen Properties von `rex_fragment` eine Kollision. Das sin neben `filename` noch `vars` und `decorator.`

**Comment by DanielWeitenauer** [comment]
Eventuell ließe sich das Problem verkleinern, indem man ein obskures Prefix für die Properties nutzt. Z.B. wie bei den Magic Methods zwei Unterstriche o.ä.
