### ISSUE TITLE
Quickstart::Verbesserungswünsche

### ISSUE THREAD

**Issue by jbnmn** [redaxo/docs#12]
Erstmal ein großes Lob für das Tutorial!

Selbst ich als absolutes Greenhorn konnte innerhalb der vorgesehenen 15min. Redaxo 5_3_0 installieren.
Allerdings ist mir eine Kleinigkeit zum Ende hin aufgefallen:

Auch wenn man Module und Template nach Anleitung installiert und eingefügt hat sieht man auf der eigentlichen Website davon nichts. Dort steht lediglich ein kleiner Verweis, dass man einen Startartikel festlegen soll. Ich als Neuling muss mich aber erst einmal im Redaxo zurecht finden um dann zu merken, dass ich auch noch Artikel für die Homepage im Struktur-Reiter festlegen muss. Vielleicht sollte man die Info direkt zu Anfang irgendwo unterbringen damit man immer wieder zwischendurch mal auf seiner Website gucken kann was bis dato so passiert ist.

Den Rest der Doku sollte ich natürlich auch noch lesen ;-)

**Comment by skerbis** [comment]
Danke https://github.com/redaxo/docs/commit/82de90e99d406c8bf2e3c23f087b18c661e56f6b

**Comment by alexplusde** [comment]
@jbnmn vielen Dank! Das ist wertvolles Feedback. Wenn dir noch mehr auffällt / einfällt, dann lass es uns wissen.

Bist du in Slack?

**Comment by jbnmn** [comment]
@alexplusde immer wieder gerne, wenn ich was sehe werde ich mich auf jeden Fall melden! 
Und leider nein, aktuell bin ich nicht in Slack.

**Comment by alexplusde** [comment]
@jbnmn in der Redaxo-Slack-Community findest du auf jeden Fall weitere Starthilfe und Ansprechpartner, wenn du mal nicht weiter weißt https://friendsofredaxo.slack.com/

**Comment by jbnmn** [comment]
@alexplusde der gute @skerbis muss mir erst nochmal die ein oder andere Sache beibringen, dann lass ich mich da gerne blicken :-)

**Comment by skerbis** [comment]
Brav!
