### ISSUE TITLE
rex_sql::->factory()->getTables()-Methode fehlt

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#123]
https://github.com/redaxo/docs/blob/master/datenbank-queries.md

wird bspw. im Cronjob-Addon verwendet.

**Comment by skerbis** [comment]
Übernehmen aus: 
https://github.com/redaxo/redaxo/blob/84aea24d31933fc0249f5ac0eccd00cf09084679/redaxo/src/core/lib/sql/sql.php#L1500
