### ISSUE TITLE
rex_list konkrete (kopierfertige) Beispiele liefern

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#125]
In Slack wurde der Syntax für `setColumnFormat()` in https://redaxo.org/doku/master/listen nicht verstanden. Wenn ich mir die Doku so durchlese, würde ich es als Neuling auch nicht verstehen. Gut wären hier einfache und konkret kopierbare Anwendungsbeispiele.

**Comment by aeberhard** [comment]
Hier mal ein paar Beispiele, die ich evtl. auch noch erweitere
https://gist.github.com/aeberhard/c0bd05d7dd13a493f67c4e0c3b06fe8a

**Comment by alxndr-w** [comment]
Ich möchte die Anzahl offener Issues in meinem GitHub-Account reduzieren. Ich finde das zwar nach wie vor hilfreich, arbeite aber selbst quasi gar nicht mehr mit rex_list außer für die Datenübersicht in YForm. Gerne darf sich dem jemand anderes widmen.
