### ISSUE TITLE
Docs erforderlich für 5.9

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#129]
Die gecheckten sind bereits erledigt

- [x] Empfehlung für PHP Versionsangabe in der Package @skerbis

- [x] Installation um aktuelle Screenshots ergänzen und auf utf8mb4 eingehen. @skerbis

- [ ] Modulauswahl im Artikel kann besser vom Admin beeinflusst werden #2891
https://github.com/redaxo/redaxo/pull/2891

- [x] Mail-Logging und Archivierung (@skerbis)
https://github.com/redaxo/redaxo/pull/3185 

- [x] Logging, **neuer Log-Ordner**, rex_path::log (@skerbis)
https://github.com/redaxo/redaxo/pull/3217

- [x] console setup:run (@skerbis)
https://github.com/redaxo/redaxo/pull/3118

- [x] Setup utf8mb4 (@skerbis)
Voraussetung: **MySQL 5.7.7** or **MariaDB 10.2**
https://github.com/redaxo/redaxo/pull/3150

- [ ] DB-Typ und spez. Version abfragen 
https://github.com/redaxo/redaxo/pull/3147

- [x] Rex_Navigation Ankerinhalt bearbeitbar
https://github.com/redaxo/redaxo/pull/3092

- [ ] rex_sql_table --> Verwendung weiterer Datenbanken möglich (dbid) 
https://github.com/redaxo/redaxo/pull/3049

- [ ] ensureGlobalColumns() nutzen
https://github.com/redaxo/redaxo/pull/2963

- [ ] Neue Rex_Navi_Funktion: @alexplusde @DanielWeitenauer - Beispiele bitte. 
Move tag generation to dedicated methods for easy overriding
https://github.com/redaxo/redaxo/pull/1426

- [x] Templates können via Key geladen werden (@skerbis)
https://github.com/redaxo/redaxo/pull/2892

- [ ] Strukturrechte add/edit/delete
https://github.com/redaxo/redaxo/pull/3182

addCategory[]
editCategory[]
deleteCategory[]
addArticle[]
editArticle[]
deleteArticle[]

**Comment by alexplusde** [comment]
An der navigation_factory wurde mein PR nicht angenommen - daher weiß ich auch nicht, wie die jetzt funktioniert. Da halte ich mich raus.

**Comment by gharlan** [comment]
> An der navigation_factory wurde mein PR nicht angenommen - daher weiß ich auch nicht, wie die jetzt funktioniert. Da halte ich mich raus.

Doch, deiner ist drin und auch drin geblieben. Ich hatte ja Daniels PR noch so angepasst, dass er sich mit deinem Feature verträgt.

**Comment by alexplusde** [comment]
Oh, das habe ich nicht gesehen. Danke! Nja gut, dann sehe ich da für mich was in Hannover...

**Comment by skerbis** [comment]
Ich habe jetzt auf der Startseite der Doku einen Bereich **Neues in dieser Version** angelegt um auf große Neuerungen hinzuweisen.
