### ISSUE TITLE
Änderungen in Redaxo 5 in Doku aufnehmen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#13]
https://github.com/redaxo/redaxo/wiki/Aenderungen-in-REDAXO-5

Die Seiteninhalte des Wikis, insb. diese, gehören eigentlich auch in die Doku, oder nicht?
-> im Wiki dann direkt auf die neue Doku verlinken

**Comment by skerbis** [comment]
@alexplusde gerne

**Comment by polarpixel** [comment]
Ist auch erledigt.
