### ISSUE TITLE
Installer Webservice URL erwähnen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#132]
`https://www.redaxo.org/de/ws/`

manche Provider meinen es sehr gut mit einem und blockieren den Aufruf zum Webservice.

Wurde in Slack dieses Jahr 2-3 bereits gefragt. Welche Rubrik?

**Comment by gharlan** [comment]
Ggf. kann man in dem Zusammenhang auch `socket_proxy` (config.yml) erwähnen.
Denn bei manchen muss man es ja auch über einen Proxy laufen lassen, der sich dort hinterlegen lässt.

**Comment by skerbis** [comment]
Kannst du das näher erläutern @gharlan ?
