### ISSUE TITLE
Neue Rubrik: (Backend)Übersetzung

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#133]

**Comment by skerbis** [comment]
- Sprachdateien
- [Redaxo i18n-Keys (zur Laufzeit) ergänzen](https://github.com/redaxo/docs/issues/93)
- Mithilfe bei der Übersetzung
- Werkzeuge

**Comment by alexplusde** [comment]
Eventuell kann man auch was übernehmen aus der Anleitung redaxo 4 zu redaxo 5 mit den empfohlenen Addons. Xoutputfilter sprog und aw_tranlator.

Auch damit verwandt: YRewrite Konfigurationen für verschiedene Sprachen.

**Comment by skerbis** [comment]
Es geht um das Backend

**Comment by alexplusde** [comment]
Ah!

**Comment by alxndr-w** [comment]
@skerbis `completed` oder `not planned`? Kannst du mich im docs-Repo wieder hinzufügen, bin da wohl rausgeflogen.

**Comment by skerbis** [comment]
Thema Übersetzung muss ganz anders  angegangen werden.
