### ISSUE TITLE
REDAXO-Variablen nicht Variablen nennen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#135]
REX_ARTICLE, REX_VALUE... usw. sind keine Variablen, sie werden aber oft so bezeichnet in den Docs und daher wird immer wieder angenommen, es würde sich dabei um Variablen (oder PHP-Konstanten) handeln. In Wirklichkeit sind es Platzhalter, die ersetzt werden. Ich finde, das sollten wir fortan auch so bezeichnen.

Ein Beispiel aktuell war die Frage, warum sich "REDAXO-Variablen" nicht auskommentieren lassen.

**Comment by alexplusde** [comment]
@skerbis wärst du damit einverstanden?

**Comment by skerbis** [comment]
Jein - wenn man REDAXO VARS als Framework eigen sieht dann sind es schon Variablen des Frameworks. Tatsächlich sind sie sogar eher Methoden oder Funktionen. Dahinter kann sich so viel verstecken

**Comment by alexplusde** [comment]
* Variablen (weitehin) 👎
* Komponenten 👍
* Platzhalter ❤
* Shortcuts 👀

Ich könnte mir auch sowas vorstellen wie REX_VAR-Shortcuts oder REX_VAR-Platzhalter, damit das `VAR` von `VARIABLE` nicht ganz verschwindet.

**Comment by skerbis** [comment]
Also der bislang offizielle Wortlaut ist: https://redaxo.org/doku/master/redaxo-variablen
Ich würde es dabei belassen.  Platzhalter wären es wenn es ein Template-System wäre. 

@staabm @gharlan @dergel @tbaddade  
Ich möchte das nicht entscheiden, da das Wording schon ewig besteht.

**Comment by staabm** [comment]
In meinem Wortschatz waren es auch schon immer variabln (auch wenn es streng genommen vllt kein sind).

> das man sie nicht auskommetieren kann

Dazu könnte man vllt ein issue aufmachen..ggf. Kann man da was machen

**Comment by tbaddade** [comment]
Ein CMS welches ebenso diese Notation verwendet, bezeichnet diese als Platzhalter. Wobei ich aber gegen eine „Umbenennung" wäre. Ich finde den jetzigen eigenen Begriff REX_VAR am stimmigsten.

**Comment by alexplusde** [comment]
@tbaddade es geht nicht darum, sie nicht REX_VAR nennen zu dürfen. Es ging darum, ob von REDAXO-Variablen die Rede ist.

**Comment by skerbis** [comment]
Mann sollte beachten, dass sie nicht immer REX_VAR irgendwas  heißen müssen, zB REX_VIDEO: REX_*

**Comment by skerbis** [comment]
Thesaurus gefragt: 

KATEGORIEN: Mathematik
Platzhalter · Stellvertreter · Variable · Veränderliche
UNTERBEGRIFFE:
stochastische Größe · stochastische Variable · Zufallsgröße · ...
abhängige Variable · endogene Variable · erklärte Variable · ...
Einflussvariable · erklärende Variable · exogene Variable · ...
Alle anzeigen
 >> Ändern

**Comment by tbaddade** [comment]
> es geht nicht darum, sie nicht "REX_VAR" nennen zu dürfen. Es ging darum, ob von "REDAXO-Variablen" die Rede ist. 

Das ist mir bewusst und deshalb bin ich für den Eigenbegriff REX_VAR.

> Mann sollte beachten, dass sie nicht immer REX_VAR irgendwas heißen müssen, zB REX_VIDEO

REX_VIDEO ist auch eine REX_VAR ... `rex_var_video`, verwechsle es nicht mit REX_VALUE

**Comment by skerbis** [comment]
REX_VAR @alexplusde

**Comment by alexplusde** [comment]
Ok, vielleicht liegt ein Missverständnis vor: Was ist dann bspw. `REX_TEMPLATE[1]`? Weder REX_VALUE, noch REX_VAR?

**Comment by skerbis** [comment]
Eine REX_VAR : https://github.com/redaxo/redaxo/blob/59f6507706caa51d9778f53fa1db7c8f278ff982/redaxo/src/addons/structure/plugins/content/lib/var_template.php#L8
