### ISSUE TITLE
Status active in Navigation fehlt

### ISSUE THREAD

**Issue by CaptainMik** [redaxo/docs#137]
In der Sidebar der Dokumentation fehlt der active-Status auf dem Menüpunkt auf dem man sich gerade befindet. Wäre irgendwie übersichtilicher, wenn der Navigationspunkt auf dem ich mich befidne irgendwie hervorgehoben würde.

**Comment by staabm** [comment]
@schuer das hast du kürzlich gefixed, oder?

**Comment by schuer** [comment]
@staabm Ja, das habe ich neulich gefixt.
