### ISSUE TITLE
Hinweis auf rex_view::setJsProperty()

### ISSUE THREAD

**Issue by aeberhard** [redaxo/docs#138]
fehlt noch in der Doku.

Hier https://redaxo.org/doku/master/addon-assets

**Comment by skerbis** [comment]
Kannst du erläutern was es tut?

**Comment by staabm** [comment]
Damit kann man eine variable aus php heraus im javascript des backends verfügbar machen

Beispiele https://github.com/redaxo/redaxo/search?q=setJsProperty
