### ISSUE TITLE
Addon-Struktur - Hilfe zum Addon help.php vs. readme.md

### ISSUE THREAD

**Issue by aeberhard** [redaxo/docs#139]
https://redaxo.org/doku/master/addon-struktur

Hier ist noch die help.php beschrieben. Mittlerweile wird aber die readme.lang.md verwendet!?

**Comment by alexplusde** [comment]
Nicht automatisch, es werden Angaben in der package.yml benötigt.

**Comment by aeberhard** [comment]
@alexplusde ich glaube schon automatisch aber habe gerade gesehen dass readme doch auch beschrieben ist.

Daher hier close :)

**Comment by alexplusde** [comment]
Stimmt. Dennoch: Das sollte verbindlich erklärt werden. (opt. Reiter am Addon und pflicht Hilfe in der Addon-Liste)

**Comment by staabm** [comment]
Die help.php existiert auch immernoch und ist ein legitimer weg, wenn man z.b. Die hilfe programatisch erstellen will/muss und nicht nur statische texte drinnen liegen

**Comment by alexplusde** [comment]
Das stimmt. Damit Addon-Entwickler jedoch überhaupt weniger Hürden haben, eine Doku verfügbar zu machen, würde ich die README.md als ersten Weg empfehlen. Das meiste kann man damit abdecken und schlägt auch zwei Fliegen mit einer Klappe, wenn man diese auf GitHub direkt lesen kann, sofern das Addon sich dort befindet.

**Comment by skerbis** [comment]
Ich habe den Text verändert und die help.php als alternative Lösung beschrieben.
