### ISSUE TITLE
Suchfunktion

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#14]
Suche auf redaxo.org ggf. Noch mehr inhalte durchsuchen als nur die doku

Man könnte auch für eine enfache 1. version ein formular bauen was die github suche des docs reposes verwendet

**Comment by alexplusde** [comment]
Ihr habt doch jetzt einen Search_it Experten im Haus ;)

**Comment by skerbis** [comment]
So langsam wird eine Suche nötig.

**Comment by erraiva** [comment]
Ja bitte eine Suche allein für die Doku.

**Comment by staabm** [comment]
als workaround: man kann aktuell übr die github suche dieses repository durchsuchen.

**Comment by erraiva** [comment]
… das ist ne Idee, danke und schönes WE :-)
Heinz

**Comment by dtpop** [comment]
Thanks to Gregor, Jan, Marcel! Sehr schön geworden und Gruß aus Zorge!
