### ISSUE TITLE
Docker: Kurze Info und Anleitung

### ISSUE THREAD

**Issue by schuer** [redaxo/docs#141]
- Was ist es und wofür braucht man es?
- Wo gibt es die Images?
- Wie nutzt man sie?

**Comment by alexplusde** [comment]
* Gegenüberstellung zu anderen bekannten Workflows wie klassischem FTP-Upload, XAMPP/MAMP und Vorteile nennen.
* Link zum Image
* Erklärung, was von FOR in den Images voreingestellt wurde
* Kurzanleitung in wenigen Schritten
* Veröffentlichung / Staging
* Parallelbetrieb mehrerer Images / Projekte erläutern

**Comment by schuer** [comment]
Ich werde es sicherlich kurz und knapp halten, aber danke für die Anregungen!

**Comment by alexplusde** [comment]
@schuer dann bitte nicht wundern, wenn viele den Einstieg scheuen. Auch meine genannten Punkte kann man kurz halten / darauf eingehen.

**Comment by schuer** [comment]
Ich werde die Ressourcen, die ich für den Task aufbringen kann und _möchte_, sehr bedacht einsetzen. Insofern danke für die Anregungen!

**Comment by alexplusde** [comment]
Das verstehe ich. Ich möchte aber auch, dass sich der Task generell lohnt - sagen wir so: Ab dem Zeitpunkt, an dem es mir gelingt, das durchzuführen, kannst du davon ausgehen, dass ich die Anleitung erweitere, um den Einstieg zu erleichtern.

In Hannover habe ich es irgendwie umgangen, mit dir das Ganze mal anzuschauen 😔

**Comment by pschuchmann** [comment]
Wenn du Unterstützung brauchst @schuer, sag Bescheid. Gegenlesen kann ich immer 😊

**Comment by schuer** [comment]
Inzwischen gibt es bei FOR die Neuauflage von REDAXO mit Docker: https://github.com/FriendsOfREDAXO/redaxo-mit-docker/
Es ist gleichzeitig ein ausführliches Tutorial und eine lauffähige Entwicklungsumgebung.

Weiterhin wurde ein Newsartikel veröffentlicht: https://redaxo.org/cms/news/redaxo-mit-docker/

Frage ist nun, ob noch zusätzlich irgendwas in die REDAXO-Docs soll? Ich hatte ein bisschen drüber überlegt und am Ende das Gefühl, dass es nicht mehr unbedingt notwendig ist.
— Was meint das Doku-Team dazu, wollt ihr was haben? Und wenn ja, wo genau und in welcher Form?

**Comment by alexplusde** [comment]
Ich denke auch, dass das ein FOR-Thema ist und kein REDAXO-Thema

**Comment by schuer** [comment]
Also, dann würde ich hier schließen. Falls nochmal Bedarf aufkommen sollte, gerne Bescheid geben. :)
