### ISSUE TITLE
rex_list Hinweis auf Linkparameter start bei setColumnParams() 

### ISSUE THREAD

**Issue by aeberhard** [redaxo/docs#149]
Bei setColumnParams() sollte als zusätzlicher Parameter 'start=xx' mitgegeben werden.
Dadurch wird z.B. beim löschen eines Datensatzes wieder die letzte Seite angezeigt statt
zum Anfang der Liste zu springen.
Beispiel kommt mit dem demo_addon.
Das sollte dann auch dokumentiert werden. Evtl. kann dann der Code aus dem demo_addon verwendet werden.

z.B. 
`$list->setColumnParams('delete', ['func' => 'delete', 'id' => '###id###', 'start' => $start]);`

**Comment by alexplusde** [comment]
Und weitere Tipps zu rex_list gleich mit eintragen: https://github.com/FriendsOfREDAXO/tricks/issues/99

**Comment by alxndr-w** [comment]
Das steht bereits als Beispiel bei `setColumnParams()`:
https://github.com/redaxo/docs/blob/main/listen.md#setcolumnparams

close?

**Comment by aeberhard** [comment]
Ja dann kann hier zu :)
