### ISSUE TITLE
Dokus erforderlich für 5.11

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#163]
- [x] Tabellen via rex_sql_util kopieren https://github.com/redaxo/redaxo/pull/2956

https://github.com/redaxo/redaxo/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Add+to+Docs%22

**Comment by alexplusde** [comment]
Siehe auch #143 #129

**Comment by skerbis** [comment]
@alexplusde einfach ein meinem Beitrag dazu schreiben. ... ich hab's erstmal nur geöffnet.
