### ISSUE TITLE
Vorlage wird scheinbar nicht mehr beachtet

### ISSUE THREAD

**Issue by tbaddade** [redaxo/docs#170]
Ich meine diese hier
https://github.com/redaxo/docs/blob/master/_vorlage.md

Darin sind bewusst Kommentare enthalten, damit das documentation AddOn die Dateien auf redaxo.org korrekt ausgeben kann.

Durch diverse Anpassungen jetzt, müsstet ihr ggf. auch das AddOn jetzt anpassen bzw. genauer beobachten ob noch alles funktioniert. Auch das PDF dabei beachten. Das wird auch über das AddOn generiert.

**Comment by alexplusde** [comment]
@tbaddade ich fände es gut, wenn wir uns an einem der originären markdown-Standards orientieren. Siehe: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

**Comment by tbaddade** [comment]
> ich fände es gut, wenn wir uns an einem der originären markdown-Standards orientieren

Ich meine das ist auch so. Es orientierte bisher sich an das Original-Markdown ohne irgendwelche Erweiterungen. Wenn jetzt Erweiterungen einfließen, dann müsstet ihr vermutlich auch das AddOn erweitern.

**Comment by alexplusde** [comment]
Welche Erweiterungen meinst du z.B.?

**Comment by tbaddade** [comment]
> Welche Erweiterungen meinst du z.B.?

Bisher sollte Code eingerückt werden. Aktuell werden "Fenced code blocks" verwendet, teilweise sogar mit `php/js` notiert

In der Vorlage steht das:
https://github.com/redaxo/docs/blob/master/_vorlage.md#code

Wie gesagt, ich will nur darauf hinweisen, dass das AddOn `documentation` ggf. dann eine Anpassung benötigt. Dort werden die markdown-Dateien abgeholt, angepasst und Inhalte teilweise noch ersetzt. Das sollte ihr jedenfalls im Hinterkopf haben, wenn ihr jetzt vom traditionellen Markdown auf "Github Flavored Markdown", "Markdown Extra" oder welche Variante auch immer geht.

**Comment by alexplusde** [comment]
Ok, danke für den Hinweis. Ich hatte es im entsprechenden PR vermerkt und @skerbis hatte da sein OK gegeben. Ich habe jedenfalls keinen Zugriff auf das docs-Plugin und ich denke, wir sollten da kooperativ vorgehen.

**Comment by alexplusde** [comment]
hier entsteht kein Todo aus diesem Issue.

**Comment by skerbis** [comment]
Die Notierung /Auszeichnunh des Codes wird schon lange so gemacht - das muss in der Vorlage aktualisiert werden.  Seit wann weiß ich nicht mehr aber sicher seit einem unserer internen Treffen

**Comment by skerbis** [comment]
@tbaddade PDF Export habe ich gerade getestet. Geht. Hin und wieder kommt es aber zu einem Timeout. Liegt aber nicht am Markup oder so vielmehr an dompdf. Das ist bekanntlich sehr lahm. 
Die _Vorlage werde ich anpassen.

**Comment by alexplusde** [comment]
Vielleicht ungünstige CSS-Regeln? Bilder PNG statt JPG? Das hätte dann nichts mit unseren Änderungen zu tun. Müsste man nur optimieren.

**Comment by skerbis** [comment]
es sind zu viele Artikel für dompdf. Das Problem kann ich in anderen Installationen gerade bei der verwendeten Version reproduzieren. In neueren Versionen ist es "etwas" besser.
