### ISSUE TITLE
Debugging: Whoops mehr erläutern

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#172]
**Welches Kapitel?**
https://github.com/redaxo/docs/blob/master/debugging.md

**Was fehlt?**

- [ ] * Whooops: Integration des System-Editors
- [ ] * Markdown-Button: Kopieren der Daten als Markdown zum melden an REDAXO
- [ ] * Templates / Module: Durch anklicken direkt ins Backend springen.

**Comment by crydotsnake** [comment]
Falls du Unterstützung brauchst ✋

**Comment by alexplusde** [comment]
Gerne :)

**Comment by crydotsnake** [comment]
Können es Ja zusammen machen

**Comment by alexplusde** [comment]
Ein Entwurf von dir würde mich zeitlich entlasten.

**Comment by crydotsnake** [comment]
Weiß leider nicht wie ich anfangen soll, bzw wie und wo es hin soll.. und wie es aussehen soll.

**Comment by staabm** [comment]
Unbedingt auf den video der REDAXOhour hinweisen: https://www.youtube.com/watch?v=yYhXgTMuEf0

**Comment by crydotsnake** [comment]
Kümmere ich mich drum! :) @staabm

**Comment by crydotsnake** [comment]
https://github.com/redaxo/docs/pull/174

**Comment by skerbis** [comment]
scheint erledigt
