### ISSUE TITLE
Fehler/Korrektur: Titel ausgeben als title-Tag

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#176]
**Beschreibe, was falsch ist.**
![image](https://user-images.githubusercontent.com/3855487/82191229-7fb07600-98f2-11ea-8af7-3f90664f8cf3.png)

**Fehler**
Überall die gleichen Titel

**Comment by schuer** [comment]
Muss im Website-Repo gefixt werden. PR liegt vor.
