### ISSUE TITLE
Mein Addon ist nicht abwärtskompatibel, was tun?

### ISSUE THREAD

**Issue by novinet-markusd** [redaxo/docs#178]
Bei ständigen aktualisieren eines Addon´s, kann es vorkommen, das man sich entscheided Klassen/Funktionen etc. anders zu gestallten. Dies kann zwangsweise dazu führen, dass die neue Version des Addon´s nicht mehr in Projekten funktionert, die das Addon fest verwurzelt verwenden.

Hier am Beispiel einer Klasse Kunde.php:

Version 1.0.0:

    kunde.php

    class Kunde {
        public function __construct($company_name, $contact_person) {}
     }

Für Version 2.0.0 ist geplant das Kunden nun über ihre Id konstruiert werden:

    kunde.php
     
    class Kunde {
        public function __construct($id) {}
    }

**Lösung:**

Nutze die update.php die im Root Verzeichnis des Addons angelegt werden kann.

    update.php

    // initialisiere $addon
    $addon = rex_addon::get("mein_addon_name");

    // aktuelle Version des Addons speichern
    $currentVersion = $addon->getVersion();

    // mindest Version festlegen
    $minVersionRequired = "2.0.0";

    // nutze rex_string::versionCompare um die Versionen zu vergleichen
    if (rex_string::versionCompare($currentVersion, $minVersionRequired, "<")) {
        
        // Setzte Error Message
        $message = "Version " . $currentVersion . " kann nicht auf Version " . $minVersionRequired . " aktualisiert werden.";
        
        // Schmeiße den Fehler mit der Error Message, das Addon wird dadurch nicht aktualisiert
        throw new rex_functional_exception($message);
    }

Jetzt wird verhindert, dass das Addon nicht mehr auf Version 2.0.0 aktualisiert werden kann.

**Nachteile:** 
- Projekte mit der alten Version sind dann final auf der letzten Version vor 2.0.0 und bleiben da
- Der update check kannn umgangen werden, wenn man das Addon desinstalliert, dann aktualisert, dann wieder installiert wird

**Comment by gharlan** [comment]
Ich würde das Update nicht versuchen zu verhindern. Es muss für die Leute ja nun mal irgendwie auch eine Möglichkeit geben, auf die neue Version zu wechseln. Und das anschließend manuelle Anpassungen nötig sind, ist bei einem Major-Update zu erwarten. 

Es wäre aber sehr gut, wenn wir im Installer Major-Updates speziell kennzeichnen, und vielleicht vor dem Update auch nochmal nachfragen, ob man es wirklich möchte (https://github.com/redaxo/redaxo/issues/2401).

**Comment by skerbis** [comment]
Es gibt das eine oder andere AddOn, das dies macht. Es sollte aber nicht der Normalfall sein. 
Aus meiner Sicht ist es eher ein Trick.

https://github.com/FriendsOfREDAXO/tricks/issues/240

rex_string::versionCompare Könnte man aber noch in der Doku besser erklären
