### ISSUE TITLE
Fehler/Korrektur: Inhaltsverzeichnis-Syntax fehlerhaft bei R4/5

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#180]
**Beschreibe, was falsch ist.**
https://redaxo.org/doku/master/upgrade-v4-v5
Layout vom Inhaltsverzeichnis wird verkackt, betrifft auch #159 /cc @staabm 
 
**Fehler**
![image](https://user-images.githubusercontent.com/3855487/82896298-051cd180-9f56-11ea-9ae9-cb001f04bedb.png)

**Korrektur**
Entweder automatisieren, oder für diese Seite fixen

**Comment by staabm** [comment]
was genau im screen ist der fehler?

**Comment by tbaddade** [comment]
Verstehe das Problem auch nicht

Hier das Original, sieht genauso aus
https://github.com/redaxo/docs/blob/master/upgrade-v4-v5.md

**Comment by alexplusde** [comment]
Unten die letzten Punkte haben eine Trennlinie erhalten, der Abstand stimmt nicht, die Aufzählungszeichen fehlen. Sehr ihr das nicht?!

**Comment by tbaddade** [comment]
> Unten die letzten Punkte haben eine Trennlinie erhalten, der Abstand stimmt nicht, die Aufzählungszeichen fehlen. Sehr ihr das nicht?!

Wenn du in der Zwischenzeit nur die[ md-Datei anpasst](https://github.com/redaxo/docs/commit/b21f9bcac2492916903c8b0034412bcc5db0355b), dann kommt auch eine unterschiedliche Darstellung auf redaxo.org zustande. Ich habe jetzt eben die aktualisierte Datei geladen und es erscheint wie gewollt. Oder ich verstehe immer noch nicht den eigentlichen Fehler.

**Comment by alexplusde** [comment]
Das habe ich gemacht, nachdem ihr da „nichts seht“. Ich hatte/habe keinen Bock auf solche Diskussionen.

**Comment by tbaddade** [comment]
Fazit: Markdown Markup war in der Datei falsch notiert worden.
