### ISSUE TITLE
Fehler/Korrektur: „Hinweis“ leer

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#181]
Mit iphone angeschaut, sieht man hier eine „Hinweis-Box“ aber ohne hinweis drinn?

https://www.redaxo.org/doku/master/basis-addons#console

![9C42E3B0-057B-4FDA-90A9-415502333C61](https://user-images.githubusercontent.com/120441/83101269-41fddb00-a0b2-11ea-95bb-35c5a630474f.jpeg)

**Comment by crydotsnake** [comment]
Ja. Sieht bei mir auch so aus.

**Comment by alexplusde** [comment]
Lösung: Zeilenabstand in der md-Datei entfernen

**Comment by crydotsnake** [comment]
Ohmann.. *entfernt... Tschuldigung! 🤦

**Comment by crydotsnake** [comment]
Fehler ist Behoben! :blush:

**Comment by staabm** [comment]
danke
