### ISSUE TITLE
Fehler/Korrektur: Apidocs-Links überprüfen

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#190]
**Beschreibe, was falsch ist.**
Am besten schickst du einen Link zur enstsprechenden Codestelle in diesem Repository.
https://www.redaxo.org/doku/master/service-urls

ganz am Ende der Seite bspw. 
Die URLs haben sich alle geändert, da eine neue Apidocs-Software eingesetzt wird.

**Comment by skerbis** [comment]
Habe ich schon an einigen Stellen gemacht
