### ISSUE TITLE
Docs fehlen für 5.11 und 5.12

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#204]
Diese müssen noch angelegt werden, damit sie auf der Website erscheinen.

Ich möchte mir - wenn alles klappt - Ende Januar einen Tag nehmen, indem ich hier einige Issues abarbeite.

**Comment by skerbis** [comment]
Wir fahren direkt mit 5.12 fort. Freue mich wenn du mithilfst. Ich denke ich gehe das nächstes WE an.
