### ISSUE TITLE
User: rex_user / rex_user_role

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#215]
**Kapitel-Titel**
Es gibt noch kein Kapitel zu Benutzern und Rollen.

**Themen und Inhalte**
Welche Fragestellungen / Funktionen sollen in diesem Kapitel beantwortet werden. Gibt es evtl. bereits Material oder Issues in diesem oder anderen Repos dazu?

- Was ist ein REDAXO-Benutzer, 
- wo können Rechte für Benutzer und Rollen vorgenommen werden (bei Benutzer, aber auch bei der Addon-Programmierung und bei der Einstellung von Templates)
- Abgrenzung zu YCom und Frontend-Benutzern

**Comment by alxndr-w** [comment]
@skerbis die Zuweisung des Issues an dich erfolgte automatisch durch das Issue-Template, das war kein bewusster Vorgang.

**Comment by skerbis** [comment]
https://redaxo.org/doku/main/benutzerverwaltung

**Comment by alxndr-w** [comment]
Ich war eher bei der Auflistung hier, dass da auch auf rex_user eingegangen wird.
![image](https://user-images.githubusercontent.com/3855487/117187417-2c258980-addc-11eb-8d7b-2123c26da2a5.png)

**Comment by skerbis** [comment]
Gerne ergänzen
https://redaxo.org/doku/main/benutzerrechte
