### ISSUE TITLE
FOR tricks

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#23]
Sollten die FOR tricks irgendwo aus der doku heraus verlinkt sein?

**Comment by skerbis** [comment]
Zumindest vielleicht hier: https://redaxo.org/support/ressourcen/
Ich bin dafür. Bin aber auch dafür, dass es jemanden gibt, der die Tricks gegencheckt und ggf. prüft ob sich das eine oder andere nicht besser in allgemeinen Dokus (von AddOns) aufgehoben fühlt.

**Comment by cukabeka** [comment]
Ja, das gibt es echt teils überschneidungen: Dinge, die ich in "Doku" erwarten würde, sind in "Tricks" und umgekehrt

**Comment by skerbis** [comment]
@cukabeka Beispiele?

**Comment by alexplusde** [comment]
Mit der neuen FOR-Tricks-Website sehe ich eine Würdigung dieser in der offiziellen Doku als notwendig.

**Comment by skerbis** [comment]
Sind jetzt im letzten Abschnitt verlinkt
