### ISSUE TITLE
Empfohlene Anforderungen an Server-Umgebung erweitern

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#232]
Core und Plugins erfordern ggf. bestimmte Bibliotheken (intl! pdo_mysql!, iconv?, gd?, imagick?, ...) - diese werden weder auf redaxo.org im Downloads-Bereich, noch in der Doku explizit aufgelistet.

Ich würde empfehlen, alle Anforderungen des Cores und der Addons - gerne auch der häufigsten Y- und FOR-Addons (z.B. YRewrite) zumindest aufzulisten.

Use Case: Hoster fragt, was die Anforderungen ans Paket sind und was freigeschalten werden soll.

**Comment by tbaddade** [comment]
Unsere MIndestanforderungen für den YDeploy-Workflow sind derzeit:

- SSH-Zugang
- MySQL (möglichst >= 5.7.7) oder MariaDB (möglichst >= 10.2.0)
- PHP 8.1
- Linux
    - rsync muss installiert sein
- Apache
    - mod_rewrite
- PHP-Extensions:
    - zwingend: fileinfo, gd, iconv, intl, mbstring, pdo, pdo_mysql, pcre, session, tokenizer, xml
    - möglichst: curl, imagick, opcache, zip
- E-Mail-Versand … SMTP Daten

**Comment by skerbis** [comment]
ich close hier es gibt ja auch noch https://github.com/redaxo/docs/issues/291

**Comment by alxndr-w** [comment]
@skerbis ich weiß nicht warum, aber meine Liste unterscheidet sich von der von Koala.
