### ISSUE TITLE
Bei Code-Beispielen Dummy-Output mit angeben

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#24]
So bekommt man einen konkreten Eindruck davon, was eine Klasse macht.

Denn wieder Helmut Kohl einst sagte: 
>Entscheidend ist, was hinten rauskommt.

Aufgefallen bei `rex_list` und `rex_form`, könnte aber auch andere Teile der Doku betreffen.
bspw. hier https://redaxo.org/doku/master/listen

**Comment by polarpixel** [comment]
@alexplusde Was meinst Du denn genau? Da sind doch Beispiele drin, wie man beispielsweise ien Liste ausgibt?

**Comment by alexplusde** [comment]
den Ausgabe-Code.

Da steht bspw.

```
$list = rex_list::factory('SELECT name,vorname,plz,ort,telefon FROM rex_adressen');
$list->show();
```

Aber was für HTML wird da jetzt erzeugt?

**Comment by staabm** [comment]
> Aber was für HTML wird da jetzt erzeugt?

das html kann und wird sich mit redaxo versionen ändern.
es ist sehr umfangreich und es in die doku reinzubringen hat keinen mehrwert?

**Comment by tbaddade** [comment]
@alexplusde Meinst du jetzt eher einen Screenshot oder das tatsächliche HTML im Quelltext?

**Comment by alexplusde** [comment]
Dann in dem Fall wohl eher einen Screenshot. Prinzipiell aber eben etwas, aus dem deutlich hervorgeht, was einen konkret erwartet.

**Comment by alexplusde** [comment]
> das html kann und wird sich mit redaxo versionen ändern (es ist daher sehr aufwändig zu pflegen). Es ist sehr umfangreich und es in die doku reinzubringen hat keinen mehrwert?

Ich sehe das nicht so. Im Gegenteil: Wenn sich etwas ändert, ist es wichtig, das mit in der Doku festzuhalten.
