### ISSUE TITLE
Lib Beschreibung in addon-struktur.de

### ISSUE THREAD

**Issue by gupi** [redaxo/docs#28]
Im addon-struktur.md steht zum Ordner Lib folgendes:
_Autoload-Ordner, alle hier gefundenen PHP-Classes und Functions werden automatisch eingebunden._
Das ist nur für die Klassen zutreffend! Funktionen werden nicht automatisch eingebunden. Die müssen über die boot.php eingebunden werden!

**Comment by skerbis** [comment]
Alles klar, komisch bei den Verdorren hatte ich das geschrieben. 👍 
@gupi Danke
