### ISSUE TITLE
Änderungen REDAXO 4 zu 5 fehlen ab 5.10

### ISSUE THREAD

**Issue by aeberhard** [redaxo/docs#283]
https://redaxo.org/doku/5.9/aenderungen-v4-v5

Ich finde die Seite immer wieder hilfreich! Ab Version 5.10 fehlt die in der Doku.

**Comment by alxndr-w** [comment]
https://redaxo.org/doku/main/upgrade-v4-v5

**Comment by aeberhard** [comment]
Ah ja, komisch habe ich gestern gar nicht gesehen ;)
