### ISSUE TITLE
Linkziele gibt es nicht mehr -> 404 Fehlerseite

### ISSUE THREAD

**Issue by Koala** [redaxo/docs#288]
https://github.com/redaxo/docs/blob/3374e0daba5ec675ea0c67ec6f766744b327213e/tutorial-quickstart.md?plain=1#L38-L39

Die Verweise auf getbootstrap führen zu 404-Seiten. Gibt es Alternativen? 

Nur so eine Idee ...
Evtl. würde es für den Zweck auch ein Addon tun, welches nur die für das Beispiel benötigten grundlegenden CSS und JS bereitstellt?

**Comment by skerbis** [comment]
Die Seite ist veraltet und wurde vorerst  aus der Navi entfernt.
