### ISSUE TITLE
Seite mit Auflistung der Mindestanforderungen bei PHP-Extensions

### ISSUE THREAD

**Issue by Koala** [redaxo/docs#291]
Nur ein paar Gedanken ... (noch) nichts Konkretes ...

Ich sehe noch nicht, wo das eingeordnet werden könnte. Evtl. unter Setup als letzter Punkt?
"Irgendwo" mit reinschieben ... auch nicht wirklich.
Oder gänzlich rauslassen aus der Doku und bei den [Tricks](https://friendsofredaxo.github.io/tricks/) einordnen? ... obwohl ... mit *Tricks* hat das nun auch wieder nix zu tun.

Ein kleines Script zur Prüfung existiert schon. Müsste angepasst werden. Mit Unterteilung für Core- und optionale Extensions. Obwohl ich nicht sehe, warum das getrennt werden sollte. Um eine optimale Funktion (auch zukünftig) zu gewährleisten, sollten alle aufgeführten Extensions verfügbar sein.
Was vorhanden ist, kann auch verwendet werden. 

Falls Addons noch mehr verwenden/benötigen, könnte das zusätzlich gesondert aufgeführt werden. Wäre sicher auch hilfreich.

Extensions in Form einer tabellarischen Übersicht als mögliche Grundlage für entsprechende Dokumentation:
[Übersicht der verwendeten Extensions bei Redaxo 5.15.1](https://github.com/redaxo/redaxo/issues/5767#issuecomment-1666625432)

Hier gab es auch schon ein Issue zu dem Thema: [Empfohlene Anforderungen an Server-Umgebung erweitern](https://github.com/redaxo/docs/issues/232)

Hier gibt es einen Hinweis darauf, dass das Thema eher nicht in die Doku sollte: https://github.com/redaxo/docs/pull/272#issuecomment-1498798250

**Comment by Koala** [comment]
Auf Downloadseite deutlicher Hinweis auf Extension die ausschließlich vom Redaxo Kern (ohne Vendoren) benötigt werden. 

---

Mindestanforderungen  
- PHP-Extensions:

**Comment by skerbis** [comment]
Ich sehe hier alle nötigen Anforderungen https://redaxo.org/download/core/

**Comment by Koala** [comment]
Es fehlen die Extensions in der Auflistung: `ctype, filter`

Entfernt werden kann: `pcre`
Das ist eine Builtin-Extension, die in PHP bereits fest enthalten ist.

Siehe hier und Kommentare darüber: https://github.com/redaxo/redaxo/issues/5767#issuecomment-1666935396
