### ISSUE TITLE
Notiz: Media Manager Medieninfos

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#30]
```php
$media = rex_media_manager::create($type, $file)->getMedia();
$media->getFormat();
$media->getWidth();
$media->getHeight();
$media->getHeader();
```

**Comment by alexplusde** [comment]
Wieso über create() gehen?

**Comment by skerbis** [comment]
Damit sichergestellt ist, dass die Datei existiert? I

**Comment by skerbis** [comment]
https://redaxo.org/doku/master/media-manager

**Comment by staabm** [comment]
> Wieso über create() gehen?

btw: man geht über `create` wenn man nicht schon ein `rex_managed_media` zur hand hat, sondern nur filename und type.
