### ISSUE TITLE
Hinweis auf Demo-Addons

### ISSUE THREAD

**Issue by aeberhard** [redaxo/docs#35]
Im Bereich **Addons** wäre m. E. eine Hinweisseite mit Links auf die Demo-Addons hilfreich.
Ebenso zum document-Plugin des demo-Addons.

**Comment by skerbis** [comment]
@aeberhard ja darüber haben wir schon diskutiert. Bislang wollten wir alles außerhalb des Cores rauslassen. Aber die Demo-Addons und auch die Tricks könnten einiges vereinfachen. Vielleicht ein Abschnitt nützliche Links?

**Comment by aeberhard** [comment]
Nützliche Links in einem Abschnitt wären auch gut!
Ich finde die ganzen Dinge sollten halt auch nicht untergehen und dienen ja auch zur Hilfe ...

**Comment by alexplusde** [comment]
Haben wir überhaupt gerade funktionierende Demos?

**Comment by polarpixel** [comment]
Die Community-Demo funktioniert noch nicht.
Standard-Demo und Onepage-Demo hat jeweils nur einen kleinen Bug, irgendwas ist ja immer. Lösung ist klar, ich brauche nur mal 1-2 Stunden, um das alles neu zu releasen.
Ist kein Grund, das nicht zu promoten.
Die von @aeberhard geht vermutlich auch.

**Comment by skerbis** [comment]
Ich habe einen Artikel mit interessanten Ressourcen (auf Basis eines von @dtpop) erstellt. Leider kam ich nicht dazu ihn zu veröffentlchen. Ich stelle ihn hier nun zur Diskussion und bitte um Lektorat und Korrektur.

**Comment by alexplusde** [comment]
#112 

Ich würde den Installer-Hinweis weglassen und nur notieren, wenn ein Addon NICHT über den Installer vorhanden ist.

Außerdem würde ich noch einige Addons ergänzen wollen.

Was ein bisschen blöd ist, ist, dass wir Addons an so vielen Stellen unterschiedlich erklären und jedes Mal einen Text / das Rad neu erfinden: Im Github-Repo, in der README eines Addons, im Installer in der Beschreibung - und nun auch hier.

**Comment by skerbis** [comment]
Deshalb habe ich nicht weitergemacht. Die Liste geht auch evtl. zu weit. 
@alexplusde wenn du was ändern möchtest, legt los  ... du machst nichts kaputt

**Comment by alexplusde** [comment]
Auf jeden Fall veröffentlichen. Wenn die Demos in gutem installierbarem Zustand sind, dann würde ich sie tatsächlich lieber hier erwähnt sehen: https://redaxo.org/ und im Abschnitt "Basis"

**Comment by skerbis** [comment]
Ist veröffentlicht. Ich close das hier.
