### ISSUE TITLE
Kapitel: Console

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#36]
Gibt es grundsätzlich seit 5.4 https://github.com/redaxo/redaxo/issues/1099
Neue commandos mit 5.5, Weitere mit 5.6 weitere in Planung https://github.com/redaxo/redaxo/issues/1114

**Comment by skerbis** [comment]
Wollte hierzu eine Doku schreiben, mangels Funktionalität, habe ich es gelassen. 
Die Doku wäre in etwa so gewesen: 

Console Aufrufen
Hilfe zeigen 
Kommandos zeigen (es gab aber keine)

**Comment by staabm** [comment]
Es werden jetzt ein paar nützlich dazukommen daher hab ich es mal hiwr aufgemacht.

Ich denke es würde reiche commandos zu erwähnen, grob deren idee use/case darzulegen und vllt auf vorhandene hinzuweisen dmait man mal sehen kann wie man selbst eins bauen kann.

Ich würde nicht alle verfügbaren in der doku auflisten o.ä.

**Comment by skerbis** [comment]
Es wäre schön, wenn die Core-Leute was dazu schreiben. Gerne auch nur Spiegelstriche

**Comment by staabm** [comment]
- console als admin/power-user orientierte schnittstelle für erweitere/spezielle Funktionen/Vorgänge
- Automatisierung/Skripting von Abläufen / programmatischer zugriff auf das system
- umgebung um sehr aufwändige prozesse wie migrationen o.ä. Ablaufen zu lassen, ohne timeouts etc.
- möglichkeit zur fernwartung des systems
- automatisierte veröffentlichungsprozesse der entwicklungsständen von websiten (siehe ydeploy)
- via addons erweiterbar (kommandos registrierbar, siehe ydeploy)

**Comment by staabm** [comment]
Hab mal grob zusammengeschrieben. @gharlan @dergel  @tbaddade @bloep ergänzungen?

**Comment by tbaddade** [comment]
Bin der Meinung, dass die Doku schon die Core-Commands listen könnte.

**Comment by bloep** [comment]
Finde, dass was @staabm zusammengeschrieben hat, die use-cases sehr gut darstellt und so in die Doku aufgenommen werden könnte.

**Comment by gharlan** [comment]
https://github.com/redaxo/redaxo/issues/1109

**Comment by skerbis** [comment]
habe es heute etwas erweitert: https://github.com/redaxo/docs/blob/master/console.md
