### ISSUE TITLE
Änderungen REDAXO 4 zu 5: CLANG ID

### ISSUE THREAD

**Issue by AnnikaL123** [redaxo/docs#39]
Bitte ergänzen, dass sich die "Standard" CLANG_ID von 0 auf 1 geändert hat. Somit hat die erste Sprache die ID 1 und nicht wie bisher 0

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/36604702-c62c4ebc-18be-11e8-8464-c6a9a6463273.png)

Wird sowohl in https://github.com/redaxo/docs/blob/master/redaxo-variablen.md als auch in https://github.com/redaxo/docs/blob/master/aenderungen-v4-v5.md erwähnt.
