### ISSUE TITLE
benötigte PHP-Module

### ISSUE THREAD

**Issue by bloep** [redaxo/docs#46]
Unter https://redaxo.org/doku/master/installation sollten die benötigten / optionalen PHP-Module mit aufgelistet werden.
Im Slack wurden dazu folgende genannt:
```
pdo
json
fileinfo
gd
iconv
mbstring
pdo
pdo_mysql
pcre
session
tokenizer
xml
```
Optional:
```
curl
imagick
intl
opcache
zip
```

**Comment by staabm** [comment]
da sich diese module von version zu version ändern können, würde ich diese nicht in der doku auffschreiben.

man könnte darauf verweisen dass im setup geprüft wird was nötig ist.

**Comment by bloep** [comment]
Arg, stimmt....
Dann lassen sich wahrscheinlich auch 
`private static $MIN_PHP_EXTENSIONS = ['session', 'pdo', 'pdo_mysql', 'pcre', 'tokenizer'];`
[redaxo/src/core/lib/setup/setup.php](https://github.com/redaxo/redaxo/blob/964140b18f0fabbf42be661784c7d6bb70a5c71f/redaxo/src/core/lib/setup/setup.php#L13)
nicht genauer festlegen oder? Wenn sich diese mit den Versionen ändern?

**Comment by staabm** [comment]
diese liste sollte vollständig sein. ggf. muss man sie mal gegen die liste die im slack genannt wurde vergleichen/validieren.

ich kann mir auch vorstellen dass die in slack genannten extensions ggf. welche enthalten die man für einzelne addons brauch, aber nicht für den core. die extensions der addons werden ja bei install während des setups separat geprüft, wenn in der package.yml definiert.

**Comment by bloep** [comment]
Ok, dann lassen wir das.
