### ISSUE TITLE
Link zum Bearbeiten in jedem Kapitel prominent platzieren

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#47]
Damit man einfach dazu animieren kann, selbst Korrekturen / Ergänzungen einzureichen + auch selbst schneller an der richtigen Stelle ist.

z.B. ein bearbeiten-Icon an der Navigation links oder ein Bearbeiten-Link direkt neben der Überschrift

![image](https://user-images.githubusercontent.com/3855487/41237628-4e30b94a-6d94-11e8-9079-be1bbe0f5397.png)

**Comment by skerbis** [comment]
Ist eine gute Idee. Bin dafür

**Comment by Koala** [comment]
## Vorschlag
Wie wäre es damit:

![grafik](https://user-images.githubusercontent.com/330686/216172273-d6af4b9b-46ab-4631-95c5-a082c6c6ee58.png)

## Code:
```html
<article class="docs">

  <div class="edit-bug">
      <a href="https://github.com/redaxo/docs/blob/main/intro.md?plain=1">&gt;&nbsp;Erstelle einen Pull Request</a>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="https://github.com/redaxo/docs/issues/new?body=Von%20Dokumentationsseite:%20https:%2F%2Fredaxo.org%2Fdoku%2Fmain%2Fintro %0A%0A---">&gt;&nbsp;Fehler melden</a>
    </div>
  <hr>

  <h1>Dokumentation REDAXO 5.13</h1>
``` 

## Abgeschaut auf der Seite php.net
z.B.: hier https://www.php.net/manual/de/function.isset.php 
![grafik](https://user-images.githubusercontent.com/330686/216175615-42fdc154-98f1-41f4-88ca-3a4ac836f728.png)


## Hinweis
Die Links können automagisch gebaut werden.

```
      <a href="https://github.com/redaxo/docs/blob/{{version}}/intro.md?plain=1">&gt;&nbsp;Erstelle einen Pull Request</a>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a href="https://github.com/redaxo/docs/issues/new?body=Von%20Dokumentationsseite:%20https:%2F%2Fredaxo.org%2Fdoku%2F{{version}}%2Fintro %0A%0A---">&gt;&nbsp;Fehler melden</a>
```

CSS-Tags  an eigenes Layout anpassen und im Addon einfach vor jede Seite einfügen lassen. Sollte kein großer Aufwand sein und die Dokudateien selbst bleiben davon unberühert.

Ein klarer Text ist in Betracht von Barrierefreiheit einer Grafik vorzuziehen (ein besseres Argument fällt mir grad nicht ein um meiner Überzeugung zur Textvariante Ausdruck zu verleihen  :-) )

**Comment by alxndr-w** [comment]
Statt `erstelle einen `Pull Request` vlt `Seiten bearbeiten` wie es bereits bei FOR der Fall ist, z.B.

https://friendsofredaxo.github.io/tricks/module/artikel_einbinden

![image](https://user-images.githubusercontent.com/3855487/216262425-13269b47-9d88-42ef-bca5-407ea6c4698e.png)

**Comment by tbaddade** [comment]
Ich habe einen Link unterhalb des Artikels eingefügt 

<img width="1195" alt="Bildschirm­foto 2023-02-02 um 10 51 47" src="https://user-images.githubusercontent.com/338267/216291579-6678feb3-ca82-4405-a9e7-955ce2282eba.png">

**Comment by Koala** [comment]
> Statt `erstelle einen Pull Request` vlt `Seiten bearbeiten` wie es bereits bei FOR der Fall ist, z.B.

Aus jeder Änderung wird ein PR (wenn keine Schreibrechte vorhanden sind oder auch generell?) ... aber das die Seite direkt im edit-Modus aufgerufen werden kann, hatte ich übersehen. Wieder was gelernt!
