### ISSUE TITLE
Installationsvoraussetzungen und Empfehlungen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#49]
Wie in Slack diskutiert: Es wäre super, wenn auch die Installationsvoraussetzungen und Anforderungen bzw. Empfehlungen zu älteren Versionen sowie bekannte Inkompatibilitäten notiert sind.

@gharlan 
```
R4.3/4.4: min php 4.3.2, max 5.6
R4.5/4.6: min php 5.3, max 5.6
R4.7: min php 5.3
R5: min php 5.5
```

@alexplusde
```
R4.7 kann aber auch PHP7.0, bis R5.5 erzeugt bei PHP7.2 notice.
```

bloep
```
PHP-Module für :redaxo5: https://github.com/redaxo/docs/issues/46 (bearbeitet)
```

Aus archive.org
```
1.2 Systemanforderungen
Folgende Voraussetzungen müssen zur einwandfreien Nutzung und Installation von REDAXO 4.x von Webspace, Webserver und Datenbank erfüllt werden:

PHP >= 4.3.2
MySQL (3,) 4, 5
FTP Zugangsdaten (Host, Login, Passwort)
MySQL Zugangsdaten (Host, Datenbank, Login, Passwort)
```

**Comment by cukabeka** [comment]
Gregor [23 hours ago]
Man kann es auch so formulieren: Mit PHP 5.6 läuft jede REDAXO-Version. Für PHP 7 benötigt man mindestens REDAXO 4.7


Thomas [23 hours ago]
zur Info: die Systemanforderungen finden sich in den Dokus


Thomas [23 hours ago]
REDAXO 5.x: https://redaxo.org/doku/master/installation


Thomas [23 hours ago]
REDAXO 4.x außer 4.7.x : https://redaxo.org/doku/4.6/installation


Thomas [23 hours ago]
bei 4.x gerne anpassen


Gregor [23 hours ago]
wir hatten bereits in 4.5 die mindestbedingungen angehoben

**Comment by skerbis** [comment]
Steht beim aktuellen Release jetzt immer dabei und hier: https://redaxo.org/doku/master/installation
