### ISSUE TITLE
Satz unvollständig

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#57]
Direkt unter https://github.com/redaxo/docs/blob/master/datenbank-queries.md#setdbquery

**Comment by tbaddade** [comment]
Ggf. auch einmal die [Commits](https://github.com/redaxo/redaxo/commits/master/redaxo/src/core/lib/sql/sql.php) durchgehen

U.a.
https://github.com/redaxo/redaxo/commit/7653e8128b04c40267f13ba263e5479006f14564
https://github.com/redaxo/redaxo/commit/a46a826305433d5134eba58ad19251f525c3e949#diff-043c74c6dcb9f93bd03809b49467087c
https://github.com/redaxo/redaxo/commit/a63f87fc1f1995f2b7957fd23c8b6934510adc03#diff-043c74c6dcb9f93bd03809b49467087c

**Comment by skerbis** [comment]
@gharlan  ich glaube er hat's geschrieben.

**Comment by tbaddade** [comment]
Nicht das ich wüsste … 
Wenn ich die History richtig interpretiere, hatte ich die Datei damals mit einer Überschrift angelegt. Diese hattest du dann gelöscht und deine queries.md (wo vermutlich die Inhalte reinkamen) umbenannt.

**Comment by skerbis** [comment]
Die Texte sind nicht von mir… @gharlan  oder @dtpop vielleicht?

**Comment by skerbis** [comment]
ich habe den Text korrigiert, entsprechend dem Kommentar im Quellcode. Warum die History weg ist, kann ich nicht sagen. Tatsächlich habe ich hier nur ein Rename durchgeführt, da es den Artikel doppelt gab, soweit ich mich erinnern kann.

**Comment by tbaddade** [comment]
> ich habe den Text korrigiert

https://github.com/redaxo/docs/commit/eaa83058601725444b64087483f5eb4e86ef2210

Kannst du noch die Commits von oben durchgehen und ergänzen. 
`showTables` ist zum sp. deprecated und kann auch nicht mehr statisch aufgerufen werden.

**Comment by skerbis** [comment]
@tbaddade dann sollte die Versionsnummer der Doku angehoben werden. Oder dieser Stand gespeichert werden in einem 5.5 er Branch.  Bislang haben wir nirgends Kommentare speziell zu einer Version.
