### ISSUE TITLE
rex_article::getCurrentId() vs. REX_ARTICLE_ID

### ISSUE THREAD

**Issue by DanielWeitenauer** [redaxo/docs#59]
Wenn man in einem Artikel andere Artikel über `rex_article_content` einbindet, bezieht sich `rex_article::getCurrentId()` stets auf den einbindenden Artikel. Auch beim Aufruf im eingebundenen Artikel. `REX_ARTICLE_ID` hingegen bezieht sich jeweils auf den Artikel, in dem es aufgerufen wird.

**Comment by staabm** [comment]
Ist das eine Frage? Soll sich daran was ändern?

**Comment by alexplusde** [comment]
Schätzungsweise wäre zu erwarten, dass `rex_article::getCurrentId()` im aufgerufenen Artikel auch dessen ID zurück gibt.

**Comment by DanielWeitenauer** [comment]
Das ist ein Hinweis, der in die Doku aufgenommen werden sollte. Ich habe nur noch keine passende Formulierung parat. Daher erstmal nur als Issue. In der Doku wird es aktuell wie von @alexplusde zusammengefasst beschrieben.
