### ISSUE TITLE
Q&A: Wie schütze ich meine Redaxo-Website bis zur Veröffentlichung?

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#6]
# Antwort
Wenn sich eine Redaxo-Website in der Entwicklung befindet, kann es sein, dass der Kunde bereits einen Blick auf die Website werfen will, ohne, dass die Website für Unbefugte erreichbar ist. Da auf unbestimmtem Wege auch eine halbfertige Website im Google-Index landen kann, sollte eine (Redaxo-)Website vor der Veröffentlichung durch einen der nachfolgendenen Techniken geschützt werden.

> Tipp: Für die Entwicklungs-Website nutzen viele Redaxo-Entwickler eine Subdomain, z. B. `neu.domain.de`, `dev.domain.de`, `beta.domain.de`. 

## via .htpasswd

1. vollständigen Pfad der Redaxo-Installation auf dem Webserver ausfindig machen.
2. .htpasswd-Datei genereieren, z. B. über einen [Online-htpasswd-Generator](http://www.htaccesstools.com/htpasswd-generator/)
3. .htpasswd-Datei in das Verzeichnis der Redaxo-Installation hochladen 
4. Pfad zur .htpasswd-Datei innerhalb der .htaccess-Datei hinzufügen.

> **Tipp:** Viele Hoster bieten in ihrem Webspace-Kundenmenü ebenfalls die Möglichkeit, ein Verzeichnis via .htpasswd heraus zu schützen. 

> **Hinweis:** Beim Einsatz Rewrite-AddOns (z. B. YRewrite) wird empfohlen, die .htaccess-Datei zu sichern. Bei einer erneuten Generierung der .htaccess-Datei muss auch Schritt 4 wiederholt werden.

> **Hinweis:** Dieser Schutz funktioniert bei einem Apache-Server, jedoch nicht bei einem IIS-Server.

## Via PHP http-auth

Siehe http://php.net/manual/de/features.http-auth.php, Beispiel 3.

## Via Redaxo-Login

Diesen Code am Anfang des aktivierten Templates einbauen. Hierbei muss für den Kunden ein Redaxo-Benutzer angelegt sein. Der Kunde muss sich zunächst in Redaxo einloggen, anschließend kann er die Website aufrufen. 

```
<?php
if (!rex::isBackend()) {
	if ($this->getConfig('status') != 'deaktiviert') {
		$session = rex_backend_login::hasSession();
		if (!$session) {
			header('Location: ' . $this->getConfig('url'));
			exit;
  		}
  	}
}
?>
```

## Via GET-Parameter im Template

Diesen Code am Anfang der aktiven Templates einbauen, dem Kunden anschließend die URL `meine-website.de/?vorschau=abc123` übermitteln.
```
<?php 

session_start();
$code = "abc123";
$code2 = rex_request('vorschau', 'string', 0);

// speichert den Code in der Session
if ($code2) {
  $_SESSION['vorschau'] = $code2;
}

// Ausgabe abbrechen, wenn der übermittelte Code nicht stimmt. 
if ($_SESSION['vorschau'] !== $code) {
  exit();
}

?>
```

## Siehe auch

[Diskussion auf GitHub](https://github.com/FriendsOfREDAXO/tricks/issues/8)

**Comment by skerbis** [comment]
Trick oder Doku ist hier die Frage @alexplusde

**Comment by tyrant88** [comment]
trotzdem noch den '<meta name="robots" content="noindex, nofollow">' erwähnen?

**Comment by alexplusde** [comment]
@tyrant88 ich finde, das suggeriert zu sehr Schutz, den man gar nicht hat. Ist zwar sehr einfach einzubauen, allerdings hatte ich es auch schon erlebt, dass sich Suchmaschinen darüber hinwegsetzen, oder, dass Leute Zugriff auf die Website bekommen, die ihn gar nicht haben sollen.

**Comment by tyrant88** [comment]
Ich meinte auch nur Meta zusätzlich zu den beschriebenen Maßnahmen.

 
Robots werden sich über „noindex“ hinwegsetzen, eine Suchmaschine wird das nicht tun.

 
Von: Alexander Walther [mailto:notifications@github.com] 
Gesendet: Dienstag, 24. Januar 2017 11:56
An: redaxo/docs
Cc: Norbert Micheel; Mention
Betreff: Re: [redaxo/docs] Q&A: Wie schütze ich meine Redaxo-Website bis zur Veröffentlichung? (#6)

 
@tyrant88 ich finde, das suggeriert zu sehr Schutz, den man gar nicht hat. Ist zwar sehr einfach einzubauen, allerdings hatte ich es auch schon erlebt, dass sich Suchmaschinen darüber hinwegsetzen, oder, dass Leute Zugriff auf die Website bekommen, die ihn gar nicht haben sollen.

**Comment by tbaddade** [comment]
> Trick oder Doku ist hier die Frage

sehe ich irgendwie eher im Trick Repo. Was meint ihr?

**Comment by skerbis** [comment]
Wenn es eine FAQ gibt im Manual, dann da - sonst Tricks

**Comment by skerbis** [comment]
@alexplusde soll ich's als Trick übernehmen?

**Comment by alexplusde** [comment]
Dann als Trick.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/blob/master/howto_website_sperren.md

**Comment by alexplusde** [comment]
Danke dir! @skerbis
