### ISSUE TITLE
Fehlerseiten individualisieren (ab R5.7)

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#67]
Seit R5.7 ist es möglich dass man die "Oooops Fehlerseiten" im Frontend als auch Backend individualisiert.

Die beiden Fehlerseiten sind als core-fragment im system enthalten und können z.b. via `fragments` Ordner im project addon (oder in einem beliebigen anderen addon) überschrieben werden.

Es gibt insgesamt 3 fehlerseiten im redaxo umfeld, davon sind aktuell nur 2 änderbar:
- whooops Fehlerseite, die man nur sieht wenn man als admin im backend eingeloggt ist. Diese enthält debugging informationen und taucht sowohl in frontend und backend auf. sie ist nicht änderbar.
![image](https://user-images.githubusercontent.com/120441/47963157-5ab62400-e028-11e8-9148-bb6093675551.png)
- die oooops Fehlerseite im redaxo backend (als fragment `core/be_ooops.php` überschreibbar), wenn man nicht als admin user im backend eingeloggt ist
![image](https://user-images.githubusercontent.com/120441/47963163-673a7c80-e028-11e8-9290-aa1142fdb1a9.png)
- die oooops Fehlerseite im frontend (als fragment `core/fe_ooops.php` überschreibbar), wenn man nicht als admin user im backend eingeloggt ist
![image](https://user-images.githubusercontent.com/120441/47963121-a4523f00-e027-11e8-8e7b-6e8a6f90ecd8.png)

eine Fehlerseite sollte eine vollständige html seite sein (inkl. html, head, body,..), die keine externen abhängigkeiten enthält (keine externen css, js dateien, bilder oder fonts etc).

**Comment by skerbis** [comment]
Doku oder Trick? Ich tendiere zu Trick. Wie warscheinlich ist es, dass die eine Standard-Aufgabe eines Admins ist?

**Comment by alexplusde** [comment]
@skerbis wenn man zugrundelegt, dass man jedes Core-Fragment überschreiben kann, dann könnte das in die Doku und die Fehler 404-Seite ein Beispiel von vielen sein.

**Comment by skerbis** [comment]
Gute Idee

**Comment by skerbis** [comment]
https://github.com/redaxo/docs/blob/master/fragmente.md#fehlerseiten

**Comment by alexplusde** [comment]
Danke!
