### ISSUE TITLE
EPs nicht listen und cheatsheet addon empfehlen?

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#69]
Die Liste wird nie aktuell sein: 
https://github.com/redaxo/docs/blob/master/extension-points.md#liste

**Comment by skerbis** [comment]
Ich denke hier wäre eine Ausnahme wo wir auf das AddOn verweisen sollten

**Comment by alxndr-w** [comment]
Gibt es bereits als Hinweis: https://redaxo.org/doku/5.10/addons-list#cheatsheet
