### ISSUE TITLE
Sammel-Issue: Empfehlungen zum debuggen

### ISSUE THREAD

**Issue by alexplusde** [redaxo/docs#72]
Beim Entwickeln unterstützt Redaxo den Programmierer mit verschiedenen Debug-Werkzeugen. Auch im Fehlerfall lassen sich Probleme meist schnell beheben.

Erstmal als Notiz gedacht, bitte ergänzen.

- was ist whoops? 
- Wie funktioniert der Debug-Modus und der Safe Mode
- was tun, wenn ein Modul im Backend zu einem Fehler führt, bspw. In der Struktur bei Editieren
- wie führen auch notices zu whoops: siehe https://github.com/redaxo/redaxo/pull/2193#issuecomment-437668713
- Wie nutze ich dump()

**Comment by alexplusde** [comment]
* rex_logger vorstellen.

**Comment by alexplusde** [comment]
rex_logger Parameter aufzählen:

https://github.com/php-fig/log/blob/master/Psr/Log/LogLevel.php

**Comment by skerbis** [comment]
Systembericht und Errormail ab 5.7

**Comment by alexplusde** [comment]
Sorry, muss ich wieder aufmachen: `dump` und `safemode` fehlen.
