### ISSUE TITLE
Base Pfad == Frontend Pfad ?

### ISSUE THREAD

**Issue by Koala** [redaxo/docs#78]
"Base Pfad" und "Frontend Pfad" haben den selben Inhalt (rex_path::base).
Soll das so sein?

[https://github.com/redaxo/docs/blob/master/pfade.md](https://github.com/redaxo/docs/blob/master/pfade.md) Zeile 59 und 69

> <a name="base"></a>
> ### base
> 
> Gibt den Base Pfad der übergebenen Datei zurück
> 
> Beispiel:
> `rex_path::base('media/meinbild.jpg')` => '/htdocs/meinverzeichnis/media/meinbild.jpg'
> 
> 
> 
> <a name="frontend"></a>
> ### frontend
> 
> Gibt den Frontend Pfad der übergebenen Datei zurück
> 
> Beispiel:
> `rex_path::base('media/meinbild.jpg')` => '/htdocs/meinverzeichnis/media/meinbild.jpg'
>

**Comment by skerbis** [comment]
Danke für den Hinweis, es sollte für das Frontend heißen: rex_path::base
Bei einem "normalen" Hosting sind diese Pfade tatsächlich identisch. Sobald man REDAXO in einem Unterordner installiert sieht man den Unterschied.

**Comment by alexplusde** [comment]
Wieso close, das sollte man dann doch als Korrektur mit aufnehmen?

**Comment by tbaddade** [comment]
> Wieso close, das sollte man dann doch als Korrektur mit aufnehmen?

Wurde mir diesem Commit erledigt https://github.com/redaxo/docs/commit/bbc261237b0ef4d3b15449c8e0892a98b7540473

@skerbis Wenn du einen Commit machst kannst du sowas in der Art notieren

> Pfade angepasst, fixed #78

Damit würde das Issue hier direkt geschlossen und der Commit landet hier als Referenz

**Comment by skerbis** [comment]
@tbaddade ah danke, das war mir nicht bekannt ❤️❤️
