### ISSUE TITLE
Navigationen erstellen mittels rex_navigation::factory() 

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#8]
Aus Tricks übernehmen?
https://github.com/FriendsOfREDAXO/tricks/blob/master/templates_navigation-factory.md

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/tricks/issues/12

**Comment by alexplusde** [comment]
Unbedingt! Vielleicht aufdröseln in einzelne kopierbare Vorlagen - auf Neulinge wirkt der Code doch recht üppig.

Als ich diesen Abschnitt unserem Azubi erklärt habe, war es wichtig, zu erwähnen, dass return: true; / return: false; darüber entscheidet, ob der Eintrag letztlich auch angezeigt wird.

Vielleicht ein Beispiel anhand gängiger Aufgabenstellungen erklären, z.B. in Kombination mit Metainfos (Navigationspunkt im Header zeigen / nicht zeigen / per CSS ausblenden, damit bspw. nur im mobilen Menü sichtbar)

**Comment by polarpixel** [comment]
Dieses Issue ist ja erledigt.
