### ISSUE TITLE
package.yml: Neue Property `ignore_installer` ergänzen

### ISSUE THREAD

**Issue by schuer** [redaxo/docs#83]
Auf der Seite [Package (package.yml)](https://github.com/redaxo/docs/blob/master/addon-package.md) müsste noch die Property `ignore_installer` ergänzt werden, die mit REX 5.7 neu hinzugekommen ist, siehe PR: redaxo/redaxo#2352

**Comment by skerbis** [comment]
@schuer https://github.com/redaxo/docs/blob/master/addon-package.md#ignore
Bitte prüfen und ggf. ergänzen :-)

**Comment by schuer** [comment]
Passt, danke @skerbis!

**Comment by skerbis** [comment]
Danke @schuer
