### ISSUE TITLE
Empfohlenen Umgang mit Properties ändern

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#84]
https://github.com/redaxo/redaxo/pull/2315

**Comment by skerbis** [comment]
@gharlan 

```php 
$project = rex_addon::get('project');

$project->setProperty(...);
$project->getProperty(...);
```

Aktuell weiß ich nicht wo in der Doku ein guter Platz dafür ist. Ein best practice Beitrag wäre wohl ganz gut. Oder sowas wie Empfehlungen vom Core?

**Comment by alexplusde** [comment]
Vielleicht auch erstmal ein Trick mit Anwendungsbeispielen?

**Comment by skerbis** [comment]
@alexplusde Es ist ein best practice bzw. eine ausdrückliche Empfehlung des Cores und gehört in die Doku. Es fehlt aktuell aber ein entsprechender Punkt.

**Comment by alexplusde** [comment]
Ich würde dann einen eigenen Menüpunkt vorschlagen und an geeigneter Stelle querverweisen (Module, Templates, ggf. Addons)

**Comment by skerbis** [comment]
@alexplusde ich habe einen PR zu den "Eigenschaften" erstellt.
