### ISSUE TITLE
passwort via console zurücksetzen

### ISSUE THREAD

**Issue by staabm** [redaxo/docs#86]
unter https://redaxo.org/doku/master/passwort-vergessen sollte erwähnt werden, wie man via redaxo console das passwort zurücksetzen kann

**Comment by skerbis** [comment]
@staabm wie geht das denn?

**Comment by tbaddade** [comment]
Per Konsole das eingeben (dazu musst du im bin Ordner sein)
`console user:set-password <user> [<password>]`

**Comment by skerbis** [comment]
@tbaddade danke … ich schreibe mal rein

**Comment by skerbis** [comment]
https://github.com/redaxo/docs/commit/904451c3201280699f238f6adc405027b5015cf9

**Comment by staabm** [comment]
mega, danke euch 2.

**Comment by tbaddade** [comment]
Helfen könnten auch das hier `console` … das listet dir Kommandos und Optionen.

**Comment by skerbis** [comment]
Ja wir brauchen eine Consolen-Hilfe … das wollte mal jemand angehen … hmm war das ich?

**Comment by tbaddade** [comment]
> Ja wir brauchen eine Consolen-Hilfe

Die Hilfe existiert bereits … Man müsste nur das Kommando kennen … Oder meintest du etwas anderes?

**Comment by staabm** [comment]
ich glaube er meint ein doku-kapitel

**Comment by skerbis** [comment]
Ich habe mir den Consolen-Artikel notiert und werde ihn etwas überarbeiten
