### ISSUE TITLE
Fehler in der Doku bei Extension Points

### ISSUE THREAD

**Issue by metaphon** [redaxo/docs#88]
$name = $ep->getParams(); FALSCH
$name = $ep->getName(); RICHTIG

**Comment by skerbis** [comment]
Wo genau?

**Comment by alexplusde** [comment]
@metaphon danke für die Meldung, möchtest du gleich einen PR dazu erstellen? Wenn du weißt, wie?

**Comment by skerbis** [comment]
ist schon erledigt, es gab schon vorher ein Issue dazu @alexplusde

**Comment by skerbis** [comment]
@metaphon Danke
