### ISSUE TITLE
Anwender :: Docs im CMS

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#89]
Während einer Schulung gestern regte ein Kunde an, den Abschnitt **Anwender** der Doku im System selbst darzustellen. Ist dies irgendwie möglich? Mir gefällt die Idee. Vielleicht über ein kleines AddOn, das ähnlich arbeitet wie auf REDAXO.org?

**Comment by alexplusde** [comment]
Im Endeffekt müssten die Docs mit der REDAXO-Installation geliefert werden, dann wäre es sehr einfach. Wie man das spiegelt weiß ich jedoch nicht.

Dann könnte man aber auch gleich die ganze Doku auch für Nicht-Anwender rübernehmen. Eine Blaupause, das Docs-Addon, gibt es ja bereits.

**Comment by skerbis** [comment]
Vielleicht mache ich was in FOR dazu. Ich close erstmal.
