### ISSUE TITLE
rex_addon::get(...) statt $this. More explicit, less magic.

### ISSUE THREAD

**Issue by tbaddade** [redaxo/docs#91]
https://github.com/redaxo/redaxo/pull/2482

Die Doku müsste hierzu angepasst werden.
Beispiele und der Grund für das Umbenennen finden sich im PR.

**Comment by staabm** [comment]
vllt noch kurz ergänzend: `$this` funktioniert natürlich weiterhin. aber wenn man die explizite variante wählt ist es für nicht redaxo kenner einfacher zu verstehen was/warum passiert

**Comment by skerbis** [comment]
Es ist schwierig aktuell die richtige Stelle dafür zu finden um darauf hinzuweisen.

**Comment by staabm** [comment]
> Es ist schwierig aktuell die richtige Stelle dafür zu finden um darauf hinzuweisen.

Ich denke man muss nicht drauf hinweisen. Es reicht vermutlich bestehende code-beispiele anzupassen

**Comment by skerbis** [comment]
Ist zB. Hier geschehen: https://redaxo.org/doku/master/eigenschaften#eigene_properties

**Comment by skerbis** [comment]
An weiteren Stellen entfernt 
auch hier: https://github.com/redaxo/docs/commit/375506aa6b4df7276bd5d4bbc3bac7d422fb5214

Sollte reichen Close
