### ISSUE TITLE
Mehrsprachigkeit: locale über Meta-Infos erwähnen

### ISSUE THREAD

**Issue by alxndr-w** [redaxo/docs#93]
Siehe https://github.com/tbaddade/redaxo_sprog/issues/53

hier erwähnen: https://www.redaxo.org/doku/master/mehrsprachigkeit

**Comment by skerbis** [comment]
was genau?

**Comment by alexplusde** [comment]
Meta-Info-Feld für Sprache namens locale anbieten, das befüllen mit dem elends langen String wie `de_DE@euro.UTF-8,de_DE.UTF-8,de.UTF-8,ge.UTF-8` und dann im Template zu oberst oder in der boot.php ausgeben.

`setlocale(LC_ALL, explode(",",rex_clang::getCurrent()->getValue('locale')));`

**Comment by skerbis** [comment]
würde auf meinen Servern nicht wirklich funktionieren.

**Comment by alexplusde** [comment]
Warum? Und sollte nicht gerade dann ein erprobter Königsweg dokumentiert sein?

**Comment by alexplusde** [comment]
Wie würdest du hier weiter verfahren? Was würde auf deinem Server funktioinieren?
