### ISSUE TITLE
JS_IMMUTABLE, Async, JS_DEFERED

### ISSUE THREAD

**Issue by skerbis** [redaxo/docs#98]
```
 rex_view::addJsFile($addon->getAssetsUrl('javascripts/bootstrap.js'), [rex_view::JS_IMMUTABLE => true]);
```

https://github.com/redaxo/redaxo/blob/e1d6dfba23929062b14387bb51e84c6e46f1a64c/redaxo/src/addons/be_style/boot.php#L43-L48

**Comment by skerbis** [comment]
@staabm @gharlan 
Könnt Ihr die Gründe und den Sinn für immutable bitte kurz skizzieren?

**Comment by staabm** [comment]
@skerbis immutable nimmt man dann wenn eine resource (identifiziert durch eine url) sich inhaltlich nie verändert.

anders gesagt: sobald sich eine resource inhaltlich verändert, ändert sich auch ihre url (cache buster in url z.b.).

der browser brauch eine resource die immutable definiert also niemals validieren sondern kann diese blind aus dem browser cache verwenden

**Comment by staabm** [comment]
siehe auch http://bitsup.blogspot.com/2016/05/cache-control-immutable.html

**Comment by skerbis** [comment]
@staabm - Danke, das sollte reichen

**Comment by skerbis** [comment]
Notiz: Beispiel mit allen Optionen
``php
rex_view::addJsFile(
  rex_url::addonAssets('tinymce4', 'tinymce/tinymce.min.js'),
  [rex_view::JS_IMMUTABLE => false, rex_view::JS_ASYNC => true, rex_view::JS_DEFERED => true]
);
```

**Comment by skerbis** [comment]
https://github.com/redaxo/docs/blob/master/addon-assets.md#javascripte
